zsh_start_time=$(python3 -c 'import time; print(int(time.time() * 1000))')
# binary path
export PATH=$PATH:$HOME/.local/bin
export PATH=$PATH:$HOME/.cargo/bin
export PATH=$PATH:$HOME/appimages

# library path
export LIBRARY_PATH=$LIBRARY_PATH:/usr/include
zsh_end_time=$(python3 -c 'import time; print(int(time.time() * 1000))')
echo "Shell init time: $((zsh_end_time - zsh_start_time)) ms"
