# binary path
export PATH=$PATH:$HOME/.local/bin
export PATH=$PATH:$HOME/.cargo/bin
export PATH=$PATH:$HOME/appimages
export PATH=$PATH:$HOME/go/bin

# library path
export LIBRARY_PATH=$LIBRARY_PATH:/usr/include
