zsh_start_time=$(python3 -c 'import time; print(int(time.time() * 1000))')
plugins=(
    ssh
    sudo
    colored-man-pages
    git
    zsh-autosuggestions
    zsh-syntax-highlighting
)
source $OMZ_PATH/oh-my-zsh.sh
zsh_end_time=$(python3 -c 'import time; print(int(time.time() * 1000))')
echo "Shell init time: $((zsh_end_time - zsh_start_time)) ms"
