zsh_start_time=$(python3 -c 'import time; print(int(time.time() * 1000))')
alias ls=eza
alias find=fd

alias vim=nvim
alias vi=nvim
alias v=nvim
alias nivm=nvim
alias nimv=nvim
alias vnim=nvim
zsh_end_time=$(python3 -c 'import time; print(int(time.time() * 1000))')
echo "Shell init time: $((zsh_end_time - zsh_start_time)) ms"
