zsh_start_time=$(python3 -c 'import time; print(int(time.time() * 1000))')
layfetch
zsh_end_time=$(python3 -c 'import time; print(int(time.time() * 1000))')
echo "Shell init time: $((zsh_end_time - zsh_start_time))"
